#language: node_js
    
#node_js:
#  - "4"
#  - "6"

language: r
cache: packages

before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 6 # for Node v6
  - node --version

install: "npm install"
script: "npm test"

after_script:
  - npm run coveralls
